name: fakenitro

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            architecture: x64
            plat: manylinux_x86_64
            runner: ubuntu-latest
          - os: ubuntu-latest
            architecture: arm64
            plat: manylinux_aarch64
            runner: [self-hosted, linux, arm64]
          - os: windows-latest
            architecture: x64
            plat: win_amd64
            runner: windows-latest
          - os: windows-latest
            architecture: arm64
            plat: win_arm64
            runner: windows-latest
          - os: macos-latest
            architecture: x64
            plat: macosx_10_9_x86_64
            runner: macos-latest
          - os: macos-latest
            architecture: arm64
            plat: macosx_11_0_arm64
            runner: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        architecture: ${{ matrix.architecture }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirerments.txt

    - name: Build with PyInstaller
      run: pyinstaller main.py --onefile

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: fake-nitro-${{ matrix.os }}-${{ matrix.architecture }}-py3.10
        path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
          tag_name: ${{ github.run_number }}
          body: "Release for workflow run ${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
